name: Deploy Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-2

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create frontend environment file
        run: |
          cd frontend
          cat > .env.production << EOF
          NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_BACKEND_URL=https://${{ secrets.BACKEND_URL }}
          EOF

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Create frontend deployment package
        run: |
          cd frontend
          zip -r ../frontend-deploy.zip .next package.json package-lock.json public next.config.ts .env.production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Frontend to Elastic Beanstalk
        run: |
          aws s3 cp frontend-deploy.zip s3://${GITHUB_REPOSITORY_OWNER}-resumetailor/frontend-deploy-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version \
            --application-name resumetailor-${GITHUB_REPOSITORY_OWNER} \
            --source-bundle S3Bucket="${GITHUB_REPOSITORY_OWNER}-resumetailor",S3Key="frontend-deploy-${{ github.sha }}.zip" \
            --version-label "frontend-ver-${{ github.sha }}" \
            --description "Frontend deployment from GitHub Actions"
          aws elasticbeanstalk update-environment \
            --environment-name resumetailor-frontend-${GITHUB_REPOSITORY_OWNER} \
            --version-label "frontend-ver-${{ github.sha }}"

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install Backend Dependencies and Generate requirements.txt
        run: |
          cd backend
          pdm install
          pdm export -o requirements.txt --without-hashes

      - name: Create backend deployment package
        run: |
          cd backend
          zip -r ../backend-deploy.zip . -x "tests/*" "pdm.lock"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Backend to Elastic Beanstalk
        run: |
          aws s3 cp backend-deploy.zip s3://${GITHUB_REPOSITORY_OWNER}-resumetailor/backend-deploy-${{ github.sha }}.zip
          aws elasticbeanstalk create-application-version \
            --application-name resumetailor-${GITHUB_REPOSITORY_OWNER} \
            --source-bundle S3Bucket="${GITHUB_REPOSITORY_OWNER}-resumetailor",S3Key="backend-deploy-${{ github.sha }}.zip" \
            --version-label "backend-ver-${{ github.sha }}" \
            --description "Backend deployment from GitHub Actions"
          aws elasticbeanstalk update-environment \
            --environment-name resumetailor-backend-${GITHUB_REPOSITORY_OWNER} \
            --version-label "backend-ver-${{ github.sha }}"
