name: Deploy IaC

# on:
#  push:
#    paths:
#      - 'backend/compile-latex/**'
#    branches:
#      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          python -m pip install pdm

      - name: Install dependencies with PDM
        run: pdm install
        working-directory: backend

      - name: Run deploy script
        run: pdm run python deploy.py
        working-directory: backend/compile-latex

