name: Test
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      # Combined install step
      - name: Install dependencies and setup
        run: |
          npm ci --legacy-peer-deps
          npx playwright install --with-deps chromium
      
      # Run all Jest tests
      - name: Run unit and integration tests
        run: |
          npm run test -- --passWithNoTests --coverage
          npm run test:integration -- --passWithNoTests --coverage
      
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: frontend/coverage
      
      # Build and start for E2E tests
      - name: Build and start app
        run: |
          npm run build
          npm run dev & # Use dev server for better DX and reuse config
          # Wait for app to be ready
          npx wait-on tcp:3000 -t 30000
      
      # Run E2E tests
      - name: Run E2E tests
        run: npx playwright test
        env:
          CI: true
          PLAYWRIGHT_HTML_REPORT: playwright-report
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report
